/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentation.inventario;

import entidad.entitys.inventario.Supplier;
import lombok.extern.log4j.Log4j2;
import negocio.inventario.LogicalSupplier;

import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionListener;
import java.awt.event.ComponentListener;
import java.awt.event.MouseListener;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author ivanl
 */
@Log4j2
public class SupplierFrom extends javax.swing.JPanel implements ActionListener, MouseListener, ComponentListener {
    LogicalSupplier logicalSupplier = new LogicalSupplier();
    Supplier supplier;
    /**
     * Creates new form SupplierFrom
     */
    public SupplierFrom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textNameSocial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textNumberTwo = new javax.swing.JTextField();
        textDescription = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSupplier = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        jLabel1.setText("Nombre");

        jLabel2.setText("Razon Social");

        jLabel3.setText("Direccion");

        jLabel4.setText("Numero");

        jLabel5.setText("Numero 2");

        jLabel6.setText("Descripcion");

        tableSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nombre", "Empresa", "Direccion", "Numero", "Numero dos", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSupplier.addMouseListener(this);
        tableSupplier.addComponentListener(this);
        jScrollPane1.setViewportView(tableSupplier);
        if (tableSupplier.getColumnModel().getColumnCount() > 0) {
            tableSupplier.getColumnModel().getColumn(0).setMinWidth(1);
            tableSupplier.getColumnModel().getColumn(0).setMaxWidth(1);
            tableSupplier.getColumnModel().getColumn(1).setResizable(false);
            tableSupplier.getColumnModel().getColumn(2).setResizable(false);
            tableSupplier.getColumnModel().getColumn(3).setResizable(false);
            tableSupplier.getColumnModel().getColumn(4).setResizable(false);
            tableSupplier.getColumnModel().getColumn(5).setMinWidth(0);
            tableSupplier.getColumnModel().getColumn(5).setPreferredWidth(0);
            tableSupplier.getColumnModel().getColumn(5).setMaxWidth(0);
            tableSupplier.getColumnModel().getColumn(6).setMinWidth(0);
            tableSupplier.getColumnModel().getColumn(6).setPreferredWidth(0);
            tableSupplier.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("GESTION DE PROVEEDORES");

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(this);

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(this);

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel4)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNumberTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizar)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textNameSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(139, 139, 139)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNameSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNumberTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == btnAgregar) {
            try {
                SupplierFrom.this.btnAgregarActionPerformed();
            } catch (ParseException e) {
                throw new RuntimeException(e);
            }
        }
        else if (evt.getSource() == btnActualizar) {
            SupplierFrom.this.btnActualizarActionPerformed();
        }
        else if (evt.getSource() == btnEliminar) {
            SupplierFrom.this.btnEliminarActionPerformed();
        }
    }

    public void componentHidden(java.awt.event.ComponentEvent evt) {
    }

    public void componentMoved(java.awt.event.ComponentEvent evt) {
    }

    public void componentResized(java.awt.event.ComponentEvent evt) {
    }

    public void componentShown(java.awt.event.ComponentEvent evt) {
        if (evt.getSource() == tableSupplier) {
            try {
                SupplierFrom.this.tableSupplierComponentShown();
            } catch (ParseException e) {
                throw new RuntimeException(e);
            }
        }
    }

    public void mouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getSource() == tableSupplier) {
            SupplierFrom.this.tableSupplierMouseClicked(evt);
        }
    }

    public void mouseEntered(java.awt.event.MouseEvent evt) {
    }

    public void mouseExited(java.awt.event.MouseEvent evt) {
    }

    public void mousePressed(java.awt.event.MouseEvent evt) {
    }

    public void mouseReleased(java.awt.event.MouseEvent evt) {
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed() throws ParseException {//GEN-FIRST:event_btnAgregarActionPerformed
        supplier  = Supplier.builder().build();

        supplier.setName(textName.getText());
        supplier.setName_social(textNameSocial.getText());
        supplier.setDescription(textDescription.getText());
        supplier.setDireccion(textAddress.getText());
        supplier.setPhoneNumber1(textNumber.getText());
        supplier.setPhoneNumber2(textNumberTwo.getText());

        logicalSupplier.addSupplier(supplier);
        tableSupplierComponentShown();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed() {//GEN-FIRST:event_btnActualizarActionPerformed
        log.info("Actualizando categoria con ID: {}", supplier.getIdSupplier());
        logicalSupplier.updateSupplier(supplier);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed() {//GEN-FIRST:event_btnEliminarActionPerformed
        log.info("Actualizando categoria con ID: {}", supplier.getIdSupplier());
        logicalSupplier.deleteSupplier(supplier);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tableSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSupplierMouseClicked
        DefaultTableModel defaultTableModel = (DefaultTableModel)tableSupplier.getModel();
        int indexSelect = tableSupplier.getSelectedRow();

        textName.setText(defaultTableModel.getValueAt(indexSelect, 1).toString());
        textNameSocial.setText(defaultTableModel.getValueAt(indexSelect, 2).toString());
        textAddress.setText(defaultTableModel.getValueAt(indexSelect, 3).toString());
        textNumber.setText(defaultTableModel.getValueAt(indexSelect, 4).toString());
        textNumberTwo.setText(defaultTableModel.getValueAt(indexSelect, 5).toString());
        textDescription.setText(defaultTableModel.getValueAt(indexSelect, 6).toString());

        supplier.setIdSupplier(Integer.valueOf(defaultTableModel.getValueAt(indexSelect, 0).toString()));
        supplier.setName(defaultTableModel.getValueAt(indexSelect, 1).toString());
        supplier.setName_social(defaultTableModel.getValueAt(indexSelect, 2).toString());
        supplier.setDireccion(defaultTableModel.getValueAt(indexSelect, 3).toString());
        supplier.setPhoneNumber1(defaultTableModel.getValueAt(indexSelect, 4).toString());
        supplier.setPhoneNumber2(defaultTableModel.getValueAt(indexSelect, 5).toString());
        supplier.setDescription(defaultTableModel.getValueAt(indexSelect, 6).toString());
    }//GEN-LAST:event_tableSupplierMouseClicked

    private void tableSupplierComponentShown() throws ParseException {//GEN-FIRST:event_tableSupplierComponentShown
        List<Supplier> supplierList = logicalSupplier.findAllSupplier();
        DefaultTableModel defaultTableModel = (DefaultTableModel)tableSupplier.getModel();
        defaultTableModel.setRowCount(0);

        for (Supplier supplierItem : supplierList) {
            defaultTableModel.addRow(new Object[] {
                    supplierItem.getIdSupplier(),
                    supplierItem.getName(),
                    supplierItem.getName_social(),
                    supplierItem.getDireccion(),
                    supplierItem.getPhoneNumber1(),
                    supplierItem.getPhoneNumber2(),
                    supplierItem.getDescription()
            });
        }
    }//GEN-LAST:event_tableSupplierComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableSupplier;
    private javax.swing.JTextField textAddress;
    private javax.swing.JTextField textDescription;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textNameSocial;
    private javax.swing.JTextField textNumber;
    private javax.swing.JTextField textNumberTwo;
    // End of variables declaration//GEN-END:variables
}
